name: quizflutter
description: A Flutter quiz application using OpenTDB API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  flutter_local_notifications: ^17.2.3
  audioplayers: ^5.2.1
  vibration: ^2.0.0
  cupertino_icons: ^1.0.8
  html_unescape: ^2.0.0
  url_launcher: ^6.3.0  # Ajouté pour les liens cliquables
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  cached_network_image: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
hive_generator: ^2.0.1
build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3
    - assets/images/background.png  # Added for the background image
  generate: true